<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'royame_shop');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'TNJRtCuhXgt2Sv6qGRjEGg3KrO1KdnBR9CYGDAfb3UmkRIEcBmmjM75E');
define('_COOKIE_IV_', 'G1dWTayf');
define('_PS_CREATION_DATE_', '2014-10-20');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', '63c4IziFYC5j4v5EQxadz8uKdPDPuGOq');
define('_RIJNDAEL_IV_', '6wBTelO1n42vQDXJF6J5EA==');
